# Generated by Django 4.2.7 on 2023-11-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('calorias', models.IntegerField()),
                ('modopreparo', models.TextField()),
                ('carboidrato', models.FloatField()),
                ('proteina', models.FloatField()),
                ('fibra', models.FloatField()),
                ('sodio', models.FloatField()),
                ('foto', models.ImageField(upload_to='receitas/fotos/')),
            ],
        ),
    ]
