# Generated by Django 4.2.7 on 2023-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='acessos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
